# __10.1 try, throw, catch문__
## 기본 활용 방법
- try 블록 내부에서는 오류 없이 실행하고 싶은 구문들을 순서대로 기술한다.
- 오류가 발생하면 throw문을 이용해 마치 goto문을 사용한 것처럼 catch문 블록으로 넘어간다.
```C++
try
{
    ... // 작업 1
    if(error 발생)
        throw errorcode;
    ... // 작업 1
    if(error 발생)
        throw errorcode;
    ... // 작업 1
    if(error 발생)
        throw errorcode;    
}

catch(int nExp)
{
    ... // 오류 해결
}
```
---
## catch 다중화
- try-catch문에서 catch문은 여러 개로 구현할 수 있는데 이를 catch 다중화라고 한다.
- 함수를 다중 정의하는 것 처럼 예외로 들어오는 값의 자료형이 여러 경우인 경우를 각각 구현하면 된다.
- catch문 블록을 구현할 때 클래스 또한 예외에 값으로 넘길 수 있다.
- catch문 중에는 어떤 형식이든 받아들이는 catch(...)이 있다.
```C++
try{

}
catch(...){

}
```
---
# __10.2 스택 풀기__
- 함수가 함수를 호출하면 매개변수, 자동 변수, 기타 추가 정보가 모두 스택 메모리에 쌓인다.
- 함수에서 예외가 발생했을 때 스택에서 예외가 발생한 함수를 호출한 함수들이 모두 반환되도록 해야한다.
- 함수 안에서 예외를 throw해준다면 스택은 자동으로 풀리고 오류가 발생한 함수를 호출하기 전 상태로 돌아간다.
---
# __10.3 메모리 예외 처리__
- 메모리 할당에 실패하면 예외처리를 해야 할때 catch(bad_alloc &exp)를 이용하면 쉽게 해결할 수 있다.
- 메모리를 할당하는 코드를 try문 블록에 위치시키고 catch(bad_alloc &exp)를 통해 오류를 잡아내도록 하면 메모리 생성에 실패할 경우 자연스럽게 catch문 블록으로 코드의 흐름이 넘어온다.