# __예외__
- 프로그램을 실행했을 때 비정상적으로 종료하는 것을 예외라고 한다.
---
## 예외 타입
- CLR에 의해 전달되는 예외는 그 자체도 타입의 인스턴스다.
- System.NullReferenceException과 System.IndexOutOfRangeException 예외는 다름 아닌 클래스의 이름이고, 이 두 예외는 BCL의 하나의 mscorlib.dll 파일에 정의되어 있다.
- 사용자가 직접 새로운 예외 타입을 만드는 것도 가능하다.
- 이를 위한 최소한의 조건은 System.Exception을 상속받는 것이다.
- System.Exception 타입은 기본적으로 예외 정보를 구할 수 있는 속성과 메서드를 제공한다.
+ System.Exception 타입의 주요 멤버

멤버|타입|설명
---|---|---
Message|인스턴스 프로퍼티|예외를 설명하는 메시지를 반환한다.
Source|인스턴스 프로퍼티|예외를 발생시킨 응용 프로그램의 이름을 반환한다.
StackTrace|인스턴스 프로퍼티|예외가 발생된 메서드의 호출 스택을 반환한다.
ToString|인스턴스 메서드|Message, StackTrace 내용을 포함하는 문자열을 반환한다.
+ System.IndexOutOfRangeException에서의 멤버 값

멤버|대응 사례
---|---
Message|"Index was outside the bounds of the array"
Source|"ConsoleApp1|
StackTrace|at Program.Main(String[] args) in c:\temp\ConsoleApp1\Program.cs:line 9
ToString|System.IndexOutOfRangeExceptionL Index was outside the bounds of the array. at Program.Main(String[] args) in c:\temp\ConsoleApp1\Program.cs:line 9
- CLR이 콘솔 응용 프로그램을 실행하다가 처리되지 않은 예외를 만난 경우 예외 타입의 ToString 메서드로부터 반환받은 문자열을 화면에 출력한다.
---
## 예외 처리기
- 예외가 발생한 경우 CLR의 기본 처리 과정은 예외 메시지를 출력하고 프로그램을 종료하는 것이다.
- 대부분의 경우 프로그램이 강제로 종료되기보다는 예외 상황을 사용자에게 알리고 프로그램은 여전히 계속 실행되기를 원할 것이다.
- 개발자는 try / catch 구문을 사용해 예외 처리기를 제공할 수 있다.
- CLR에서는 예외가 감지된 경우 예외를 유발한 코드에 예외 처리기가 있는지 검사한다.
- 예외 처리기가 있다면 처리를 해당 예외 처리기로 넘기고, 없다면 예외 메시지를 출력하고 프로그램을 종료한다.
- 예외 처리기가 제공되지 않은 경우가 바로 "처리되지 않은 예외(unhandled exception)"다.
- 예외가 발생한다면 원인이 되는 코드부터 try 블록의 마지막 코드까지는 실행되지 않는다.
- 반면 catch 블록 내의 코드는 오직 예외가 발생한 경우에만 실행된다.
- catch 블록 내에도 try/catch를 중첩시켜서 묶는 것이 가능하다.
- finally 블록은 try 블록 내에서 예외가 발생하는 것과 상관없이 언제나 실행된다.
- 예외가 발생하지 않으면 try 블록의 코드가 실행된 다음 finally 블록의 코드가 실행되고, 예이가 발생하면 try 블록의 일부 코드가 실행된 다음 catch 블록의 코드가 실행되고 finally 블록의 코드가 실행된다.
+ 예제
```C#
int divisor = 0;

try
{
    int quotient 10 / divisor;
    Console.WriteLine("예외가 발생하지 않으면 실행됨!");
}
catch
{
    Console.WriteLine("예외가 발생하면 실행됨!");
}
finally
{
    Console.WriteLine("언제나 실행됨!");
}
```
- catch에서는 개발자가 원하는 예외만 잡을 수도 있는데, 그러자면 catch 구문에 예외 타입을 지정해야 한다.
- 다양한 유형의 예외가 try 블록에서 발생할 수 있다면 catch 블록도 다중으로 구성할 수 있다.
+ 예제
```C#
int divisor = 0;

try
{
    int quotient = 10 / divisor;
}
catch (System.NullReferenceException) { }
catch (System.DivideByZeroException) { }
catch (System.Exception) { }
```
- CLR은 catch 구문의 타입을 발생한 예외와 순서대로 비교하므로 상속 관계를 고려해 예외 타입을 지정해야 한다.
- System.Exception이 맨 위에 있으면 모든 예외가 System.Exception으로 형변환 가능하로 아래의 catch 블록에 있는 코드는 결코 실행되지 않는다.
- catch 구문에는 예외 타입뿐 아니라 예외의 인스턴스를 변수로 받는 것도 가능하다.
- 이 변수를 이용하면 해당 예외 타입에서 제공되는 모든 멤버에 접근해서 정보를 가져올 수 있다.
---
## 호출 스택
- System.Exception 타입에는 StackTrace라는 string 타입의 멤버가 있다.
- 프로그램이 실행될 때 내부적으로는 스택 자료구조가 사용되고 그 안에 메서드의 호출 과정과 메서드에 정의된 지역 변수의 데이터가 담긴다.
- 하지만 일반적으로 스택 트레이스라고 하면 메서드의 호출 과정만 포함한다.
- 호출 스택이 중요한 이유는 문제가 발생한 경우 호출 스택 정보의 유무에 따라 원인 파악의 난이도가 결정되기 때문이다.
- CLR은 예외 객체에서 StackTrace 속성을 통해 호출 스택을 제공한다.
---
## 예외 발생
- 예외를 처리하는 것도 가능하지만 임의로 발생시키는 것 또한 가능하다.
- 이를 위해 C#은 throw 예약어를 제공한다.
- 예외 타입의 인스턴스를 생성한 후 그것을 throw에 전달하면 된다.
- catch 블록 내에 있는 throw는 예외 객체 없이 단독으로 사용할 수도 있다.
- throw를 단독으로 사용할 경우 예외를 발생시킨 호출 스택이 모두 출력된다.
---
## 올바른 예외 처리
- 적어도 공용(public) 메서드에 한해서는 인자값이 올바른지 확인하고, 올바른 인자가 아니라면 예외를 발생시킨다.
- 예외를 범용적으로 catch하는 것은 스레드마다 하나만 두고 그 외에는 catch 구문에 반드시 예외 타입을 적용한다.
- try/finally의 조합은 언제든 사용할 수 있다.
- 성능상 문제가 발생할 수 있는 경우, 즉 호출 시 예외가 대량으로 발생하는 메서드가 있다면 예외 처리가 없는 메서드를 함께 제공한다.